datasets:
  data_path: data
  train_filename: train.csv
  val_filename: valid.csv
  test_filename: test.csv
fasttext:
  model_prefix: fasttext
  lemmatization: True
  remove_stopwords: False
  epochs: 100
  early_stopping_rounds: 25
  vector_size: 128
  window: 10
  alpha: 0.01
  min_alpha: 0.005
  min_count: 1
  track_loss: False
logreg:
  penalty: elasticnet
  l1_ratio: 0.5
  solver: saga
  max_iter: 1000

hydra:
  run:
    dir: outputs/baselines/${now:%Y-%m-%d-%H-%M}
  output_subdir: hydra